DROP DATABASE IF EXISTS northwestern;
CREATE DATABASE northwestern;

DROP DATABASE IF EXISTS universityofchicago;
CREATE DATABASE universityofchicago;

DROP DATABASE IF EXISTS rush;
CREATE DATABASE rush;
DROP DATABASE IF EXISTS loyolaMedicalCenter;
CREATE DATABASE loyolaMedicalCenter

DROP DATABASE IF EXISTS userInfo;
CREATE DATABASE userInfo;
